spring:
  datasource:
    url: jdbc:h2:file:./data/testdb #for persisting data between runs (bonus points)
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect